services:
  prometheus:
    image: prom/prometheus:latest
    container_name: gudit-prometheus
    ports:
      - "9090:9090"
    volumes:
          #호스트 파일 : 컨테이너 내부 경로 : 접근 권한(ro : 읽기전용 설정)
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: gudit-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    environment:
      GRAFANA_SLACK_WEBHOOK_URL: ${GRAFANA_SLACK_WEBHOOK_URL}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: gudit-redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: redis://host.docker.internal:7002
    restart: unless-stopped

  loki:
    image: grafana/loki:3.7.0
    container_name: gudit-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: gudit-alloy
    ports:
      - "12345:12345"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    environment:
      LOG_ENVIRONMENT: ${LOG_ENVIRONMENT:-performance}
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./logs:/var/log/gudit:ro
      - alloy-data:/var/lib/alloy/data
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  grafana-data:
  loki-data:
  alloy-data:
